spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tripleDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true

sql:
  init:
      schema-locations: classpath*:sql/schema.sql
      data-locations: classpath*:sql/data.sql
      mode: always